# Generated by Django 5.1.1 on 2024-10-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_productriews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRiews',
            new_name='ProductReviews',
        ),
    ]
