# Generated by Django 5.1.1 on 2024-10-17 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_productriews_productreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.customerprofile'),
        ),
    ]
