# Generated by Django 5.1.1 on 2024-10-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_productreviews_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
